//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataControl_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmp1
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpJob { get; set; }
        public decimal EmpSal { get; set; }
        public System.DateTime EmpJoinDate { get; set; }
        public int DeptId { get; set; }
    
        public virtual tblDep tblDep { get; set; }
    }
}
